server:
  port: 5133
spring:
  servlet:
    multipart:
      enabled: true
  application:
    name: my-blog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_blog_db?characterEncoding=utf-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3600
  thymeleaf:
    cache: false
logging:
    file:
      path: d:/home/blog/log
    pattern:
        # 日志打印格式
        console: '%-5level [%contextName] %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{10}.%method -%msg%n'
        # 时间格式
        dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level:
        # 目录日志级别
        org.springframework: info
        org.apache.ibatis: debug
        org.springframework.transaction: info
        org.springframework.jdbc: info
        org.mybatis: debug
        java.sql: debug